// Copyright © 2026 SculkCatalystMC. All rights reserved.
//
// This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not
// distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
// SPDX-License-Identifier: MPL-2.0

#pragma once
#include <cstdint>

namespace sculk::protocol::inline abi_v944 {

enum class AchievementIDs : std::int32_t {
    ChestFullOfCobblestone          = 7,
    DiamondForYou                   = 10,
    IronBelly                       = 20,
    IronMan                         = 21,
    OnARail                         = 29,
    Overkill                        = 30,
    ReturnToSender                  = 37,
    SniperDuel                      = 38,
    StayinFrosty                    = 39,
    TakeInventory                   = 40,
    MapRoom                         = 50,
    FreightStation                  = 52,
    SmeltEverything                 = 53,
    TasteOfYourOwnMedicine          = 54,
    WhenPigsFly                     = 56,
    Inception                       = 58,
    ArtificialSelection             = 60,
    FreeDiver                       = 61,
    SpawnTheWither                  = 62,
    Beaconator                      = 63,
    GreatView                       = 64,
    SuperSonic                      = 65,
    TheEndAgain                     = 66,
    TreasureHunter                  = 67,
    ShootingStar                    = 68,
    FashionShow                     = 69,
    SelfPublishedAuthor             = 71,
    AlternativeFuel                 = 72,
    SleepWithTheFishes              = 73,
    Castaway                        = 74,
    ImAMarineBiologist              = 75,
    SailThe7Seas                    = 76,
    MeGold                          = 77,
    Ahoy                            = 78,
    Atlantis                        = 79,
    OnePickleTwoPickleSeaPickleFour = 80,
    DoaBarrelRoll                   = 81,
    Moskstraumen                    = 82,
    Echolocation                    = 83,
    WhereHaveYouBeen                = 84,
    TopOfTheWorld                   = 85,
    FruitOnTheLoom                  = 86,
    SoundTheAlarm                   = 87,
    BuyLowSellHigh                  = 88,
    Disenchanted                    = 89,
    TimeForStew                     = 90,
    BeeOurGuest                     = 91,
    TotalBeeLocation                = 92,
    StickySituation                 = 93,
    CoverMeInDebris                 = 94,
    FloatYourGoat                   = 95,
    Friend                          = 96,
    WaxOnWaxOff                     = 97,
    StriderRiddenInLavaInOverworld  = 98,
    GoatHornAcquired                = 99,
    JukeboxUsedInMeadows            = 100,
    TradedAtWorldHeight             = 101,
    SurvivedFallFromWorldHeight     = 102,
    SneakCloseToSculkSensor         = 103,
    ItSpreads                       = 104,
    BirthdaySong                    = 105,
    WithOurPowersCombined           = 106,
    PlantingThePast                 = 107,
    CarefulRestoration              = 108,
    Revaulting                      = 109,
    CraftersCraftingCrafters        = 110,
    WhoNeedsRockets                 = 111,
    OverOverkill                    = 112,
    HeartTransplanter               = 113,
    StayHydrated                    = 114,
    MobKabob                        = 115,
    AdventuringTime                 = 116,
};

} // namespace sculk::protocol::inline abi_v944