name: xmake-linux-llvm

on:
  push:
  pull_request:

jobs:
  linux-llvm-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Install LLVM toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y clang lld libc++-dev libc++abi-dev

      - name: Show toolchain versions
        run: |
          xmake --version
          clang++ --version

      - name: Configure (LLVM Release)
        run: xmake f -p linux -a x86_64 --toolchain=clang -m release -y

      - name: Build
        run: xmake -y
